# Basic set up for three package managers

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    open-pull-requests-limit: 10
    schedule:
      interval: 'weekly'
      time: '00:00'
      day: 'sunday'
      timezone: 'America/Los_Angeles'
    commit-message:
      prefix: 'ci'
      include: 'scope'

  - package-ecosystem: 'npm'
    directory: '/'
    open-pull-requests-limit: 10
    schedule:
      interval: 'weekly'
      time: '00:00'
      day: 'sunday'
      timezone: 'America/Los_Angeles'
    commit-message:
      prefix: 'feat'
      prefix-development: 'build'
      include: 'scope'
